name: WMAR daily check

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 16 * * *'   # ~9:00 AM PT during DST

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm install --no-fund --no-audit

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run WMAR script
        run: node wmar.js
        env:
          IRS_SSN: ${{ secrets.IRS_SSN }}
          IRS_DOB: ${{ secrets.IRS_DOB }}
          IRS_ZIP: ${{ secrets.IRS_ZIP }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          GMAIL_APP_PWD: ${{ secrets.GMAIL_APP_PWD }}

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: wmar-debug
          path: |
            wmar-failure-*.png

